### ISSUE TITLE
cannot import name 'compare_ssim' from 'skimage.measure'

### ISSUE THREAD

**Issue by job2003** [tsingqguo/efficientderain#13]
Traceback (most recent call last):
  File "./validation.py", line 8, in <module>
    from skimage.measure import compare_ssim
ImportError: cannot import name 'compare_ssim' from 'skimage.measure' (C:\Users\whu_c\anaconda3\envs\yolov5\lib\site-packages\skimage\measure\__init__.py)

what's the problem

**Comment by MKFxxL** [comment]
Thanks for your question
1. Please check if the version of your skimage is 0.17.2.
2. Please check if you have installed all the dependent libraries of skimage.
