### ISSUE TITLE
Need help with a 'Value error'!

### ISSUE THREAD

**Issue by xenbaloch** [tsingqguo/efficientderain#22]
Well, that's not an issue with the code or anything. It's more like a help. I'm new with this thing, I tried to use and run your code in Pycharm(fulfilling the requirements), but when I try to run train.py, I'm getting an error "ValueError: num_samples should be a positive integer value, but got num_samples=0".  I need help regarding it, where I'm doing wrong? Thank you!

A bit more description: I tried to use the code as it is, and in models folder, I put the material downloaded from provided link "direct download: http://www.xujuefei.com/models_effderain.zip". Is there some wrong with the data path?

**Comment by Arican-Lee** [comment]
Have you solved it？
