### ISSUE TITLE
kernel可视化

### ISSUE THREAD

**Issue by Achhhe** [tsingqguo/efficientderain#28]
您好，请问论文Fig.2(c)的kernel是怎么可视化的啊，代码中kernelsize=3，而图中kernelsize=9，直接将fig.2(b)中四个空洞卷积核叠加？

**Comment by tsingqguo** [comment]
你好，为了显示kernel的效果，我们这里用了9*9，因为3*3 很难看出效果。每个channel 上的每个像素都有自己的kernel，三个channel就可以形成有颜色的kernel可视化。
